// AUTO-GENERATED by `npm run measure:pins -- --emit`.
// Do not hand-edit — rerun the script to refresh.
//
// The REAL mechanical stopping surface of every pin-side endpoint, measured
// from the converted GLB meshes. `shoulderOffset` is the axial distance from
// the endpoint's radial centre (its marker/mate frame) to the first plane
// whose cross-section can no longer pass through a VEX IQ pin hole — i.e.
// the surface that physically stops the connector against the receiving
// part. Coordinates are in the bbox-recentred frame ScenePart renders in.

export type MeasuredPinContact = {
  snapId: string
  /** Axial distance from the radial centre to the stopping plane. */
  shoulderOffset: number
  /** Axial distance from the radial centre to the shaft tip. */
  tipOffset: number
  /** Largest radius of the insertable span. */
  shaftRadius: number
  /** Radius at the stopping plane — why the connector stops there. */
  shoulderRadius: number
  /** Whole receiver layers the shaft can pass through. */
  usableLayers: number
  /**
   * False when no hole-passing material extends past the stopping plane —
   * the endpoint declares a pin the mesh does not have. Review-gated
   * rather than seated on a guessed plane.
   */
  insertable: boolean
}

export const MEASURED_PIN_CONTACTS: Record<string, MeasuredPinContact[]> = {
  "228-2500-060": [
    { snapId: "pin-front", shoulderOffset: 0.0000, tipOffset: 0.2067, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.0000, tipOffset: 0.2067, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-061": [
    { snapId: "pin-front", shoulderOffset: 0.0030, tipOffset: 0.2097, shaftRadius: 0.0906, shoulderRadius: 0.1251, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: -0.0030, tipOffset: 0.4537, shaftRadius: 0.0925, shoulderRadius: 0.1251, usableLayers: 1, insertable: true },
    { snapId: "pin-back-2", shoulderOffset: -0.2432, tipOffset: 0.2135, shaftRadius: 0.0925, shoulderRadius: 0.1251, usableLayers: 1, insertable: true },
  ],
  "228-2500-062": [
    { snapId: "pin-front", shoulderOffset: 0.0000, tipOffset: 0.4567, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.2402, tipOffset: 0.2165, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.0000, tipOffset: 0.4567, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back-2", shoulderOffset: -0.2402, tipOffset: 0.2165, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-063": [
    { snapId: "pin-front", shoulderOffset: 0.0625, tipOffset: 0.2692, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.0625, tipOffset: 0.2692, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-064": [
    { snapId: "pin-front", shoulderOffset: 0.1250, tipOffset: 0.3317, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.1250, tipOffset: 0.3317, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-065": [
    { snapId: "pin-front", shoulderOffset: 0.2500, tipOffset: 0.4567, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.2500, tipOffset: 0.4567, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-066": [
    { snapId: "pin-front", shoulderOffset: 0.3750, tipOffset: 0.5817, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.3750, tipOffset: 0.5817, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-067": [
    { snapId: "pin-front", shoulderOffset: 0.5000, tipOffset: 0.7067, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.5000, tipOffset: 0.7067, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-069": [
    { snapId: "pin-front", shoulderOffset: 0.7500, tipOffset: 0.9567, shaftRadius: 0.0906, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.7500, tipOffset: 0.9567, shaftRadius: 0.0906, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-070": [
    { snapId: "pin-front", shoulderOffset: 1.0000, tipOffset: 1.2067, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 1.0000, tipOffset: 1.2067, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-072": [
    { snapId: "pin-front", shoulderOffset: 1.5000, tipOffset: 1.7067, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 1.5000, tipOffset: 1.7067, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-073": [
    { snapId: "pin-front", shoulderOffset: -0.0362, tipOffset: 0.2079, shaftRadius: 0.0921, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.0012, tipOffset: 0.2079, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-084": [
    { snapId: "pin-front", shoulderOffset: -0.0588, tipOffset: 0.4003, shaftRadius: 0.0925, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.2990, tipOffset: 0.1601, shaftRadius: 0.0925, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-085": [
    { snapId: "pin-front", shoulderOffset: -0.0738, tipOffset: 0.6353, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 3, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.3140, tipOffset: 0.3951, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 3, insertable: true },
    { snapId: "pin-front-3", shoulderOffset: -0.5541, tipOffset: 0.1550, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 3, insertable: true },
  ],
  "228-2500-086": [
    { snapId: "pin-front", shoulderOffset: -0.0576, tipOffset: 0.3991, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.2978, tipOffset: 0.1589, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-087": [
    { snapId: "pin-front", shoulderOffset: -0.0726, tipOffset: 0.6341, shaftRadius: 0.0911, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.3128, tipOffset: 0.3939, shaftRadius: 0.0911, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-front-3", shoulderOffset: -0.5529, tipOffset: 0.1538, shaftRadius: 0.0911, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
  ],
  "228-2500-089": [
    { snapId: "pin-front", shoulderOffset: 0.0000, tipOffset: 0.7067, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.2402, tipOffset: 0.4665, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-front-3", shoulderOffset: -0.4803, tipOffset: 0.2264, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.0000, tipOffset: 0.7067, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-back-2", shoulderOffset: -0.2402, tipOffset: 0.4665, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-back-3", shoulderOffset: -0.4803, tipOffset: 0.2264, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
  ],
  "228-2500-090": [
    { snapId: "pin-front", shoulderOffset: -0.0609, tipOffset: 0.3957, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.3011, tipOffset: 0.1556, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-093": [
    { snapId: "pin-front", shoulderOffset: 0.0100, tipOffset: 0.5353, shaftRadius: 0.0807, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.2301, tipOffset: 0.2951, shaftRadius: 0.0807, shoulderRadius: 0.1250, usableLayers: 2, insertable: true },
    { snapId: "pin-back", shoulderOffset: -0.0100, tipOffset: 0.7653, shaftRadius: 0.0807, shoulderRadius: 0.1250, usableLayers: 3, insertable: true },
    { snapId: "pin-back-2", shoulderOffset: -0.2501, tipOffset: 0.5251, shaftRadius: 0.0807, shoulderRadius: 0.1250, usableLayers: 3, insertable: true },
    { snapId: "pin-back-3", shoulderOffset: -0.4903, tipOffset: 0.2850, shaftRadius: 0.0807, shoulderRadius: 0.1250, usableLayers: 3, insertable: true },
  ],
  "228-2500-097": [
    { snapId: "pin-front", shoulderOffset: -0.0738, tipOffset: 0.6353, shaftRadius: 0.0925, shoulderRadius: 0.1230, usableLayers: 3, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.3140, tipOffset: 0.3951, shaftRadius: 0.0925, shoulderRadius: 0.1230, usableLayers: 3, insertable: true },
    { snapId: "pin-front-3", shoulderOffset: -0.5541, tipOffset: 0.1550, shaftRadius: 0.0925, shoulderRadius: 0.1230, usableLayers: 3, insertable: true },
  ],
  "228-2500-098": [
    { snapId: "pin-front", shoulderOffset: -0.0320, tipOffset: 0.2121, shaftRadius: 0.0800, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: -0.0030, tipOffset: 0.4561, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "pin-back-2", shoulderOffset: -0.2432, tipOffset: 0.2159, shaftRadius: 0.0925, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-099": [
    { snapId: "pin-front", shoulderOffset: 0.1033, tipOffset: 0.1033, shaftRadius: 0.0000, shoulderRadius: 0.1463, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: -0.1033, tipOffset: 0.1033, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-1061": [
    { snapId: "pin-front", shoulderOffset: 2.0000, tipOffset: 2.2067, shaftRadius: 0.0906, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 2.0000, tipOffset: 2.2067, shaftRadius: 0.0906, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-109": [
    { snapId: "pin-front", shoulderOffset: 0.1933, tipOffset: 0.1933, shaftRadius: 0.0000, shoulderRadius: 0.1575, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: -0.0133, tipOffset: 0.1933, shaftRadius: 0.0906, shoulderRadius: 0.1258, usableLayers: 1, insertable: true },
  ],
  "228-2500-125": [
    { snapId: "barrel", shoulderOffset: -0.0148, tipOffset: 0.1918, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-1250": [
    { snapId: "peg-0", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0450, tipOffset: 0.2517, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
  ],
  "228-2500-1251": [
    { snapId: "peg-0", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-2", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-3", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-1253": [
    { snapId: "peg-0", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-2", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-3", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-4", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-5", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
  ],
  "228-2500-1254": [
    { snapId: "peg-0", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-2", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
  ],
  "228-2500-1255": [
    { snapId: "peg-0", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-2", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
  ],
  "228-2500-1258": [
    { snapId: "peg-0", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-2", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-3", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-4", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-5", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-6", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-7", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-126": [
    { snapId: "peg-0", shoulderOffset: 0.0263, tipOffset: 0.2330, shaftRadius: 0.0908, shoulderRadius: 0.1253, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0263, tipOffset: 0.2330, shaftRadius: 0.0908, shoulderRadius: 0.1253, usableLayers: 1, insertable: true },
  ],
  "228-2500-127": [
    { snapId: "peg-0", shoulderOffset: 0.0382, tipOffset: 0.2449, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0382, tipOffset: 0.2449, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
  ],
  "228-2500-128": [
    { snapId: "peg-0", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-129": [
    { snapId: "peg-0", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0908, shoulderRadius: 0.1253, usableLayers: 1, insertable: true },
  ],
  "228-2500-131": [
    { snapId: "peg-0", shoulderOffset: 0.0362, tipOffset: 0.2429, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0362, tipOffset: 0.2429, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-132": [
    { snapId: "peg-0", shoulderOffset: 0.0310, tipOffset: 0.2377, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0310, tipOffset: 0.2377, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-134": [
    { snapId: "peg-0", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-136": [
    { snapId: "peg-0", shoulderOffset: 0.0362, tipOffset: 0.2429, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0362, tipOffset: 0.2429, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-137": [
    { snapId: "peg-0", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-1470": [
    { snapId: "connector-center", shoulderOffset: 0.2441, tipOffset: 0.2441, shaftRadius: 0.0000, shoulderRadius: 0.2431, usableLayers: 1, insertable: false },
  ],
  "228-2500-1660": [
    { snapId: "pin-front", shoulderOffset: 0.1116, tipOffset: 0.1422, shaftRadius: 0.0887, shoulderRadius: 0.1017, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: 0.1101, tipOffset: 0.1422, shaftRadius: 0.0891, shoulderRadius: 0.1024, usableLayers: 1, insertable: false },
  ],
  "228-2500-170": [
    { snapId: "pin-front", shoulderOffset: 0.1225, tipOffset: 0.1225, shaftRadius: 0.0000, shoulderRadius: 0.1827, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: 0.1225, tipOffset: 0.1225, shaftRadius: 0.0000, shoulderRadius: 0.1827, usableLayers: 1, insertable: false },
  ],
  "228-2500-171": [
    { snapId: "pin-front", shoulderOffset: 0.1165, tipOffset: 0.1225, shaftRadius: 0.0904, shoulderRadius: 0.0997, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: 0.1153, tipOffset: 0.1225, shaftRadius: 0.0954, shoulderRadius: 0.1016, usableLayers: 1, insertable: false },
  ],
  "228-2500-172": [
    { snapId: "pin-front", shoulderOffset: 0.1225, tipOffset: 0.1225, shaftRadius: 0.0000, shoulderRadius: 0.2053, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: 0.1225, tipOffset: 0.1225, shaftRadius: 0.0000, shoulderRadius: 0.2036, usableLayers: 1, insertable: false },
  ],
  "228-2500-175": [
    { snapId: "pin-front", shoulderOffset: 0.2516, tipOffset: 0.2516, shaftRadius: 0.0000, shoulderRadius: 0.2443, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: 0.2509, tipOffset: 0.2516, shaftRadius: 0.0000, shoulderRadius: 0.1073, usableLayers: 1, insertable: false },
  ],
  "228-2500-192": [
    { snapId: "pin-front", shoulderOffset: 0.1619, tipOffset: 0.1619, shaftRadius: 0.0000, shoulderRadius: 0.2133, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: 0.1619, tipOffset: 0.1619, shaftRadius: 0.0000, shoulderRadius: 0.2133, usableLayers: 1, insertable: false },
  ],
  "228-2500-1934": [
    { snapId: "connector-center", shoulderOffset: 0.1194, tipOffset: 0.1194, shaftRadius: 0.0000, shoulderRadius: 0.2228, usableLayers: 1, insertable: false },
  ],
  "228-2500-2011": [
    { snapId: "connector-center", shoulderOffset: 0.4650, tipOffset: 0.4650, shaftRadius: 0.0000, shoulderRadius: 0.2450, usableLayers: 1, insertable: false },
  ],
  "228-2500-220": [
    { snapId: "peg-0", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-2", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
    { snapId: "peg-3", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0906, shoulderRadius: 0.1250, usableLayers: 1, insertable: true },
  ],
  "228-2500-2258": [
    { snapId: "pin-front", shoulderOffset: -0.0588, tipOffset: 0.4003, shaftRadius: 0.0876, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
    { snapId: "pin-front-2", shoulderOffset: -0.2990, tipOffset: 0.1601, shaftRadius: 0.0876, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-2260": [
    { snapId: "pin-front", shoulderOffset: 0.0000, tipOffset: 0.2067, shaftRadius: 0.0925, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.0000, tipOffset: 0.2067, shaftRadius: 0.0925, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-2261": [
    { snapId: "pin-front", shoulderOffset: -0.2470, tipOffset: 0.2097, shaftRadius: 0.0925, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
    { snapId: "pin-back", shoulderOffset: 0.2470, tipOffset: 0.4537, shaftRadius: 0.0896, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
    { snapId: "pin-back-2", shoulderOffset: 0.0068, tipOffset: 0.2135, shaftRadius: 0.0896, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-2268": [
    { snapId: "connector-center", shoulderOffset: 0.1600, tipOffset: 0.3667, shaftRadius: 0.0896, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-2269": [
    { snapId: "connector-center", shoulderOffset: 0.2850, tipOffset: 0.4917, shaftRadius: 0.0896, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-2271": [
    { snapId: "connector-center", shoulderOffset: 0.5350, tipOffset: 0.7417, shaftRadius: 0.0896, shoulderRadius: 0.1230, usableLayers: 1, insertable: true },
  ],
  "228-2500-2288": [
    { snapId: "peg-0", shoulderOffset: 0.0412, tipOffset: 0.2479, shaftRadius: 0.0896, shoulderRadius: 0.1233, usableLayers: 1, insertable: true },
  ],
  "228-2500-270": [
    { snapId: "peg-0", shoulderOffset: 0.0450, tipOffset: 0.2517, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
  ],
  "228-2500-271": [
    { snapId: "peg-0", shoulderOffset: 0.0450, tipOffset: 0.2517, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0450, tipOffset: 0.2517, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
  ],
  "228-2500-272": [
    { snapId: "peg-0", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0350, tipOffset: 0.2417, shaftRadius: 0.0908, shoulderRadius: 0.1252, usableLayers: 1, insertable: true },
  ],
  "228-2500-274": [
    { snapId: "peg-0", shoulderOffset: 0.0300, tipOffset: 0.2367, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0300, tipOffset: 0.2367, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
    { snapId: "peg-2", shoulderOffset: 0.0300, tipOffset: 0.2367, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
    { snapId: "peg-3", shoulderOffset: 0.0300, tipOffset: 0.2367, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
  ],
  "228-2500-277": [
    { snapId: "peg-0", shoulderOffset: 0.0450, tipOffset: 0.2517, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0450, tipOffset: 0.2517, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
  ],
  "228-2500-279": [
    { snapId: "peg-0", shoulderOffset: 0.0382, tipOffset: 0.2449, shaftRadius: 0.0909, shoulderRadius: 0.1254, usableLayers: 1, insertable: true },
  ],
  "228-2500-303": [
    { snapId: "pin-front", shoulderOffset: 0.8876, tipOffset: 0.9099, shaftRadius: 0.0944, shoulderRadius: 0.1222, usableLayers: 1, insertable: false },
    { snapId: "pin-back", shoulderOffset: 0.8876, tipOffset: 0.9099, shaftRadius: 0.0944, shoulderRadius: 0.1222, usableLayers: 1, insertable: false },
  ],
  "228-2500-368": [
    { snapId: "peg-0", shoulderOffset: 0.0427, tipOffset: 0.2494, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0427, tipOffset: 0.2494, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
  ],
  "228-2500-371": [
    { snapId: "peg-0", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
  ],
  "228-2500-372": [
    { snapId: "peg-0", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
    { snapId: "peg-1", shoulderOffset: 0.0312, tipOffset: 0.2379, shaftRadius: 0.0910, shoulderRadius: 0.1255, usableLayers: 1, insertable: true },
  ],
}
